### ISSUE TITLE
Metrics are returning 0 values

### ISSUE THREAD

**Issue by iceycake** [intelsdi-x/snap-plugin-collector-cpu#20] opened 2016-06-09 21:14 UTC
Using 0.14.0-beta of snap and plugins, this plugin is returning 0 for all the metrics

**Comment by obourdon** [comment] 2016-06-15 15:56
May be this is related to issue #18. However as there are no tags in plugin repositories which correspond to official binary releases this is hard to say for sure.

**Comment by katarzyna-z** [comment] 2016-06-27 08:39
@iceycake Could you check if the issue is fixed in your working environment with the newest version of plugin?

**Comment by marcin-krolik** [comment] 2016-06-28 17:54
@iceycake I just have checked this plugin with latest snap commit  [ed1733b](https://github.com/intelsdi-x/snap/commit/ed1733bfe09156af557fafc972b7a5a9de8a0867) and the output from task watch shows it works.

```bash
Watching Task (ea8e8f89-5322-4cb1-95f7-82fc61152f38):
NAMESPACE                                        DATA                    TIMESTAMP
/intel/procfs/cpu/all/active_jiffies             6.578378e+06            2016-06-28 19:51:54.385844871 +0200 CEST
/intel/procfs/cpu/all/active_percentage          0.5006257822277848      2016-06-28 19:51:54.385846385 +0200 CEST
/intel/procfs/cpu/all/guest_jiffies              0                       2016-06-28 19:51:54.385829205 +0200 CEST
/intel/procfs/cpu/all/guest_nice_jiffies         0                       2016-06-28 19:51:54.385848194 +0200 CEST
/intel/procfs/cpu/all/guest_nice_percentage      0                       2016-06-28 19:51:54.38581428 +0200 CEST
/intel/procfs/cpu/all/guest_percentage           0                       2016-06-28 19:51:54.385817558 +0200 CEST
/intel/procfs/cpu/all/idle_jiffies               1.532065983e+09         2016-06-28 19:51:54.385830663 +0200 CEST
/intel/procfs/cpu/all/idle_percentage            99.49937421777221       2016-06-28 19:51:54.385849813 +0200 CEST
/intel/procfs/cpu/all/iowait_jiffies             17112                   2016-06-28 19:51:54.385851326 +0200 CEST
/intel/procfs/cpu/all/iowait_percentage          0                       2016-06-28 19:51:54.385855847 +0200 CEST
/intel/procfs/cpu/all/irq_jiffies                13                      2016-06-28 19:51:54.385820319 +0200 CEST
/intel/procfs/cpu/all/irq_percentage             0                       2016-06-28 19:51:54.385857215 +0200 CEST
/intel/procfs/cpu/all/nice_jiffies               2.604713e+06            2016-06-28 19:51:54.385861505 +0200 CEST
/intel/procfs/cpu/all/nice_percentage            0                       2016-06-28 19:51:54.385832127 +0200 CEST
/intel/procfs/cpu/all/softirq_jiffies            5882                    2016-06-28 19:51:54.385862978 +0200 CEST
/intel/procfs/cpu/all/softirq_percentage         0                       2016-06-28 19:51:54.385840371 +0200 CEST
/intel/procfs/cpu/all/steal_jiffies              0                       2016-06-28 19:51:54.385823046 +0200 CEST
/intel/procfs/cpu/all/steal_percentage           0                       2016-06-28 19:51:54.385824705 +0200 CEST
/intel/procfs/cpu/all/system_jiffies             2.245938e+06            2016-06-28 19:51:54.385841929 +0200 CEST
/intel/procfs/cpu/all/system_percentage          0.1251564455569462      2016-06-28 19:51:54.385843368 +0200 CEST
/intel/procfs/cpu/all/user_jiffies               1.70472e+06             2016-06-28 19:51:54.385858603 +0200 CEST
/intel/procfs/cpu/all/user_percentage            0.37546933667083854     2016-06-28 19:51:54.385859976 +0200 CEST
/intel/procfs/cpu/all/utilization_jiffies        6.561266e+06            2016-06-28 19:51:54.385864472 +0200 CEST
/intel/procfs/cpu/all/utilization_percentage     0.5006257822277848      2016-06-28 19:51:54.385827727 +0200 CEST
```

I used below task manifest 

```json
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "workflow": {
        "collect": {
            "metrics": {
        "/intel/procfs/cpu/all/user_jiffies" : {},
        "/intel/procfs/cpu/all/nice_jiffies" : {},
        "/intel/procfs/cpu/all/system_jiffies" : {},
        "/intel/procfs/cpu/all/idle_jiffies" : {},
        "/intel/procfs/cpu/all/iowait_jiffies" : {},
        "/intel/procfs/cpu/all/irq_jiffies" : {},
        "/intel/procfs/cpu/all/softirq_jiffies" : {},
        "/intel/procfs/cpu/all/steal_jiffies" : {},
        "/intel/procfs/cpu/all/guest_jiffies" : {},
        "/intel/procfs/cpu/all/guest_nice_jiffies" : {},
        "/intel/procfs/cpu/all/active_jiffies" : {},
        "/intel/procfs/cpu/all/utilization_jiffies" : {},
        "/intel/procfs/cpu/all/user_percentage" : {},
        "/intel/procfs/cpu/all/nice_percentage" : {},
        "/intel/procfs/cpu/all/system_percentage" : {},
        "/intel/procfs/cpu/all/idle_percentage" : {},
        "/intel/procfs/cpu/all/iowait_percentage" : {},
        "/intel/procfs/cpu/all/irq_percentage" : {},
        "/intel/procfs/cpu/all/softirq_percentage" : {},
        "/intel/procfs/cpu/all/steal_percentage" : {},
        "/intel/procfs/cpu/all/guest_percentage" : {},
        "/intel/procfs/cpu/all/guest_nice_percentage" : {},
        "/intel/procfs/cpu/all/active_percentage" : {},
        "/intel/procfs/cpu/all/utilization_percentage" : {}
            },
            "process": null,
            "publish": null
        }
    }
}

```

Can you recheck?

**Comment by katarzyna-z** [comment] 2016-07-12 12:49
@iceycake Do you have any information?

**Comment by iceycake** [comment] 2016-07-12 17:43
Let me try to find time tomorrow to look into that.  Kinda busy today.

**Comment by IzabellaRaulin** [comment] 2016-07-27 09:11
@iceycake, there have been a lot of changes to both snap and snap-plugin-collector-cpu since this issue was created. It seems that this issue cannot be reproduce with the latest snap commit (as it has been checked by @marcin-krolik).  Please check is it still occurs for the latest version of both snap and this plugin as it was suggested above. However, if the issue still occurs on your system, feel free to re-open this github-issue. 

I really appreciate that you help us to keep this plugin stable.  If there is any problem in the future, feel free to open an issue.

Thank You.

**Closed by IzabellaRaulin** 2016-07-27 09:11 UTC
Labels: bug, tracked
