### ISSUE TITLE
cpu plugin reports negative values

### ISSUE THREAD

**Issue by IzabellaRaulin** [intelsdi-x/snap-plugin-collector-cpu#28] opened 2016-06-30 13:21 UTC
@ankitpatelintel reported that:

>  HI snap community,
> 
> i have just started using snap today (6 hours ago); i was able to load cpu plugin on my ubuntu machine and tried collecting some metrics. I do see results being dumped (Yey!!!! Snap works for me ); but when I looked at results; i saw bunch of negative values coming out; 
> which doesn't make sens.  attaching full log as sample.txt
> 
> 
> 2016-06-21 14:58:33.102743655 -0700 PDT|/intel/procfs/cpu/0/active_percentage**|-11.385812272204758**
> 2016-06-21 14:58:33.102746612 -0700 PDT|/intel/procfs/cpu/0/iowait_jiffies|1182
> 2016-06-21 14:58:33.10274876 -0700 PDT|/intel/procfs/cpu/1/guest_percentage|0
> 2016-06-21 14:58:33.102750752 -0700 PDT|/intel/procfs/cpu/3/user_percenta**ge|-896.7206046464441**
> 2016-06-21 14:58:33.102752202 -0700 PDT|/intel/procfs/cpu/5/idle_jiffies**|2.00001857e+08**
> 2016-06-21 14:58:33.102754392 -0700 PDT|/intel/procfs/cpu/0/utilization_jiffies|58049
> 2016-06-21 14:58:33.102755797 -0700 PDT|/intel/procfs/cpu/3/utilization_jiffies|147720
> 2016-06-21 14:58:33.102757244 -0700 PDT|/intel/procfs/cpu/5/active_percentage|**-400.44526540929417**
> 2016-06-21 14:58:33.102758572 -0700 PDT|/intel/procfs/cpu/5/guest_nice_percentage|0
> 2016-06-21 14:58:33.10276151 -0700 PDT|/intel/procfs/cpu/5/softirq_jiffies|330
> 2016-06-21 14:58:33.102762999 -0700 PDT|/intel/procfs/cpu/7/guest_nice_jiffies|0
> 2016-06-21 14:58:33.102764699 -0700 PDT|/intel/procfs/cpu/9/system_jiffies|37766
> 2016-06-21 14:58:33.102766089 -0700 PDT|/intel/procfs/cpu/0/active_jiffies|59231
> 2016-06-21 14:58:33.102767447 -0700 PDT|/intel/procfs/cpu/4/user_jiffies|20689
> 2016-06-21 14:58:33.102768984 -0700 PDT|/intel/procfs/cpu/9/nice_percentage|0
> 2016-06-21 14:58:33.102770279 -0700 PDT|/intel/procfs/cpu/0/system_jiffies|26292
> 2016-06-21 14:58:33.102771637 -0700 PDT|/intel/procfs/cpu/3/utilization_percen**tage|-941.254945723851**
> 
> [sample.txt](https://github.com/intelsdi-x/snap-plugin-collector-processes/files/326746/sample.txt)

> 

Issue moved from https://github.com/intelsdi-x/snap-plugin-collector-processes/issues/14

**Comment by obourdon** [comment] 2016-06-30 14:25
@ankitpatelintel may be you could give us the output of
`cat /etc/lsb-release ; name -a
`

**Comment by ankitpatelintel** [comment] 2016-08-17 00:07
I tested newly compiled CPU plugin and I am seeing following issues. image1:
	Most of values are nil
	Values are which are printed in >100 ; it does not make sense for *_percentage metrics.
 
One other issue is when I tried to stop task I got error.as in image 2. 
 

Thanks
Ankit 
![image1](https://cloud.githubusercontent.com/assets/12976197/17720073/ebf276ea-63d3-11e6-857e-77a8dab6afc1.jpg)
![image2](https://cloud.githubusercontent.com/assets/12976197/17720075/ebf6295c-63d3-11e6-8f25-2f916cb42baa.jpg)

**Comment by mkuculyma** [comment] 2016-08-17 08:35
@ankitpatelintel thank you for verification of the fix!

I have a suspicion that all the issues that you have encountered are caused by a bug in kernel in version 3.19.0-25-generic you are using rather than bug in Snap plugin. 
This bug manifests itself with decreasing values in /proc/stat value. 
Values in /proc/stat are jiffies so they should always increase with time or do not change. If any of the counter values in cpu columns is less than previous sample it means that /proc/stat values are incorrect – this probably happens for kernel version you are using. 

Could you run 
`for i in {1…20}; do cat /proc/stat > log.txt; sleep 10; done`
and send us the output of log.txt file?

**Comment by katarzyna-z** [comment] 2016-08-31 12:35
Fixed by pull request #34.

**Closed by katarzyna-z** 2016-08-31 12:35 UTC
